version: "3.9"
services:
  # Dentro de cada servicio podemos tener volúmenes donde ir creando subcarpetas
  zipkin:
    image: openzipkin/zipkin # Usamos image en vez de build, pues ya la tenemos preconfigurada desde Docker Hub
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "5672:5672"
      - "15672:15672" # Donde está la interfaz para monitorear
  eureka-service:
    image: eureka-service
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    ports:
      - "8888:8888"
    restart: always
  gateway-service:
    image: gateway-service
    ports:
      - "8080:8080"
    restart: always
  catalog-service:
    image: catalog-service
    ports:
      - "8091:8091"
    restart: always
  movie-service:
    image: movie-service
    ports:
      - "8092:8092"
    restart: always
  serie-service:
    image: serie-service
    ports:
      - "8095:8095"
    restart: always
  mongodb_catalog:
    command: mongod --auth
    container_name: "mondodb_catalog"
    environment:
      - MONGO_INITDB_DATABASE=catálogo
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_ROOT_USERNAME=rootuser
    image: mongo
    ports:
      - "27018:27018"
  mongodb_serie:
    command: mongod --auth
    container_name: "mondodb_serie"
    environment:
      - MONGO_INITDB_DATABASE=serie
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_ROOT_USERNAME=rootuser
    image: mongo
    ports:
      - "27017:27017"
  mongo-express_serie:
    container_name: mongo-express_serie
    environment:
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_SERVER=mongodb_serie
    image: mongo-express
    ports:
      - "8096:8096"
    restart: always
  mongo-express_catalog:
    container_name: mongo-express_catalog
    environment:
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_SERVER=mongodb_catalog
    image: mongo-express
    ports:
      - "8097:8097"
    restart: always
  mysql:
    environment:
      - MYSQL_DATABASE=movies
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
    image: mysql
    ports:
      - "3306:3306"
volumes: # Podemos agregar particiones dentro de volúmenes
  data: { }
networks: # También podemos crear networks
  default:
    name: catalog_network