eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

global-message: Configuration server is alive!

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
