spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
        - name: CountFilter
      routes:
        - id: catalogRoute
          predicates:
            - Path=/catalog/**
          uri: lb://catalog-service
        - id: musicRoute
          predicates:
            - Path=/movies/**
          uri: lb://movie-service