server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
        - name: CountFilter
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
