management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
        - name: CountFilter
      routes:
        - id: catalogRoute
          predicates:
            - Path=/catalog/**
          uri: lb://catalog-service
        - id: movieRoute
          predicates:
            - Path=/movies/**
          uri: lb://movie-service
        - id: serieRoute
          predicates:
            - Path=/series/**
          uri: lb://serie-service