info:
  app:
    description: Manage operations upon movies
    name: ${spring.application.name}
    version: 1.2.0

server:
  port: 8094

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pass
    url: jdbc:mysql://mysql:3306/movies
    username: user
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      data-locations: classpath:movie-service.sql
      mode: always