info:
  app:
    description: Manage series with their seasons and chapters
    name: ${spring.application.name}
    version: 1.0.0

server:
  port: 8095

spring:
  data:
    mongodb:
      authentication-database: admin
      host: mongodb_serie # Donde va a estar alojado el servidor de MongoDB
      database: series
      password: rootpass
      port: 27017
      username: rootuser # Como vamos a estar levantando tode con Docker vamos a utilizar perfiles por defecto