info:
  app:
    description: Manage series with their seasons and chapters
    name: ${spring.application.name}
    version: 1.0.0

queue: # Definir el nombre de la cola a través de la cual nos estamos conectando
# Se configura al momento de setear las colas (formato de mensaje y demás)
# Tipo de exchange y de cola: direct, pues tenemos sole una
  serie: # Estas configuraciones nos van a servir después si quisiéramos agregar más colas
  # Por ejemplo, una de topic que también use el nombre de movie
    name: Serie

server:
  port: 8095

spring:
  rabbitmq:
    host: rabbitmq
    password: guest
    port: 5672
    username: guest